### ISSUE TITLE
pruning-processor panicked: block checksum mismatch

### ISSUE THREAD

**Issue by kurchack-mad** [aspectron/kaspa-ng#25]
**Describe the bug**
thread 'pruning-processor' panicked at /home/runner/.cargo/git/checkouts/rusty-kaspa-b06c3fe0c8c50fcd/c020968/consensus/src/pipeline/pruning_processor/processor.rs:234:85: called 'Result:unwrap()' on 'Err' value: Error {message: "Corruption: block checksum mismatch: stored = 3884794865, computed = 314817352, type = 4 in /media/device-name/kaspa-node/kaspa-mainnet/datadir/consensus/consensus-003/004343.sst offset 428965 size 2264" }
Exiting...

**To Reproduce**
1. Fresh install Ubuntu 24.04 (likely this step is optional)
2. Download and install https://github.com/aspectron/kaspa-ng/releases/tag/v0.2.5
3. Set media location to folder on external drive
4. Click on Block DAG
5. Leave block DAG open for 24hr
6. See error

**Expected behavior**
Not to see error

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Kaspa NG version: 0.2.5

**Additional context**
I have reproduced this twice. I want to be able to leave the node on the block DAG screen forever.
Also, when this error happens I need to restart the program, which will resume working after it re-syncs the data that it missed while the program was off.
My external drive is an SSD 2 TB, plenty of free space.
I was able to reproduce it a 3rd time, 53 minutes after restarting the program.
I was able to reproduce it a 4th time, actually without clicking on the Block DAG tab, just on the logs tab.

**Comment by aspect** [comment]
Are you running in a VM?  It's an issue with your machine or Ubuntu installation. (VM/OS/Drivers/Hardware). Or unlikely but possible something may have gone wrong during the KNG build, if your built it locally from source.

KNG (and Rusty Kaspa, that handles DB) runs literally on thousands of computers of which Ubuntu is a very large part of, and no one is experiencing these types of issues.

I've previously had issues where I would use hardware and VM and all would work fine but when I/O is stressed/pressured, problems would come up (corruption is one of them). Only would occur under heavy I/O load. This, in different cases was due to 1) faulty memory 2) faulty chipset/ I/O controller 3) bad drivers; in the case of the VM it was just (in my case) Virtual Box running badly on Windows. New version solved the issue.

Closing this issue as you clearly can replicate it and no one else experiences it.

**Comment by kurchack-mad** [comment]
Thanks for the reply. It is not a VM. It is not compiled from code locally, just the downloaded release.

I am able to run the rusty Kaspa project continually without issue. I suspect there is a memory leak with kaspa-ng, as that’s usually the issue when a program runs correctly but after an amount of time it stops.

But ok we can wait until someone else encounters this issue. Thank you for all your work on Kaspa.
